language: python
sudo: required
python:
  - 3.6
before_install:
  - sh iptables_redir.sh
install:
  - python setup.py install
  - pip install codecov
script:
  - python setup.py test
after_success:
  - codecov
